### ISSUE TITLE
Simpler usage: AsyncIterator is too complex and unintuitive

### ISSUE THREAD

**Issue by buckle2000** [apollographql/graphql-subscriptions#116]
Is it possible to use this directly with node.js emitter? Current API is too complex.
Or can we just use a callback function to achieve that?

```js
const resolvers = {
  Subscription: {
    somethingChanged: {
      subscribe: (cb) => {cb(null, value)}
    }
  }
}
```

**Comment by ravenscar** [comment]
I'm also wondering what the reasoning behind using an AsyncIterator rather than an EventEmitter or Observable. 

It seems to me that in almost every case the data changes backing subscriptions would be events generated elsewhere in a system and this seems more suitable to a push paradigm rather than a pull one like AsyncIterator. Perhaps it simplifies other parts of the framework so I won't judge.

In any case the reference pubsub implementation uses an EventEmitter behind the scenes, and it is possible to pass this in during initialization, e.g.

```
import { PubSub } from 'graphql-subscriptions';
...
export const pubsub = new PubSub({
  ee: yourEventEmitterHere
});
...
const resolvers = {
  Subscription: {
    somethingChanged: {
      subscribe: () => pubsub.asyncIterator(YOUR_TOPIC),
    }
  }
}
```

**Comment by ravenscar** [comment]
On looking into it a bit more it seems that the reference implementation by the graphql team uses AsyncIterator: https://github.com/graphql/graphql-js/blob/master/src/subscription/subscribe.js so there is probably not too much the Apollo team can do about it.

**Comment by amitport** [comment]
@ravenscar Why can't they? IMHO, reference implementation does not mean much at this stage.
Additionally, AsyncIterators and Observables can live side by side if needed for some reason.

**Comment by vjpr** [comment]
I found this odd too. AsyncIterator requires pulling data using `next`. But with web-sockets I generally want to push data when events occur. Only thing I can think of is that by using pull-based they can rate-limit or something.

**Comment by jedwards1211** [comment]
Actually I think using AsyncIterators is pretty smart.  I believe they will be widespread in future reactive programming because they will be the first API built into standard JS VMs that can stream change events to observers, as well as the most generic API for doing so.

Although you pull data from an AsyncIterator, in truth they are more like a hybrid push-pull interface since the pull operation can wait on anything (for example, for a Redis wrapper to push data to it).

**Comment by jedwards1211** [comment]
@amitport while that's true, I can understand why the authors of this package would prefer to conform to the current standard from the reference implementation rather than implement something proprietary.

**Comment by jedwards1211** [comment]
@vjpr to expand on my first comment, nothing about using `AsyncIterator`s prevents pushing data over the web sockets when events occur.  `graphql` will keep waiting for the `next` payload from the `AsyncIterator`, which can be emitted at any time it chooses.  (Synchronous `Iterators` wouldn't work at all for this case, but `AsyncIterator`s work just fine).

**Comment by amitport** [comment]
@jedwards1211 bottom line I think ease of development should count for something and that the current state of it is not very good. (without disregarding other factors, like reference implementation)

also, I'm not sure what you meant by "implement something propriety". I didn't advocate specific libraries, but there are some that are easy to use, very popular, stable, free and open source. (there's nothing wrong with using a library when appropriate)

**Comment by ravenscar** [comment]
When I first commented in this thread I was fairly annoyed at having to use AsyncIterators when I though that callbacks/eventEmitters would do, however I have since changed my view as they solve a very important piece of functionality.

When you are on a mobile device and you step into an elevator/lose you connection all of your subscription events will stack up in a queue inside the AsyncIterator, and when your socket reconnects later, they will be delivered to you.

Just using callbacks/eventEmitters/observables to for subscriptions means that if you were disconnected then you would just miss out on the event.

This is a pretty strong case for using AsyncIterators when dealing with flakey websocket connections, however as others have mentioned it would be nice if this was used behind the scenes and we were given the option to use callbacks or eventEmitters directly in the API.

I guess it's new and this functionality may come.

**Comment by NeoPhi** [comment]
As mentioned above, the key reason AsyncIterator was used is that it is close to being added as a core language feature: https://github.com/tc39/proposal-async-iteration

**Comment by jedwards1211** [comment]
@amitport @buckle2000 if you guys don't want to work with AsyncIterators directly, you could work with EventEmitters and then use their function to convert to an AsyncIterator: https://github.com/apollographql/graphql-subscriptions/blob/master/src/event-emitter-to-async-iterator.ts

You could make a similar function for wrapping an RxJS stream or similar.  I think that's the other reason AsyncIterator was chosen: it's not very difficult to adapt other libraries to push data through an AsyncIterator.

@NeoPhi I think we should extract a "PushAsyncIterator" class from event-emitter-to-async-iterator.ts that has a `push` method we can call from the EventEmitter listener or whatever else we want to push data from.  That would make it easier for folks to adapt proprietary libs.  Though I think stuff like this deserves to live in its own package that graphql-subscriptions consumes.

**Comment by DxCx** [comment]
if you want to use RxJs instead of not-comfortable AsyncIterators, you are welcome to use `graphql-rxjs` (https://github.com/DxCx/graphql-rxjs)

**Comment by jedwards1211** [comment]
@DxCx does using that fork have some kind of advantages over using some utility function to wrap RxJS observables in an `AsyncIterator`?

**Comment by DxCx** [comment]
@jedwards1211 this will give you 2 things:
1. Execution engine patches to support live/defer directives
2. AsyncIterator wrappers from/to RxJs
