### ISSUE TITLE
How to write integration tests of graphql-js subscriptions ? 

### ISSUE THREAD

**Issue by aatifhussain** [apollographql/graphql-subscriptions#125]
I am using loopback-graphql-relay and I am able to test mutations and queries using mocha. I need to test subscriptions as well. 

The only guide I found on google is [this](https://medium.com/@javierfernandes/testing-graphql-subscriptions-ee14d63bf97a). But It is not working. Is there any other example?

**Comment by grantwwu** [comment]
I don't know anything about how Loopback works, but it depends on your setup - you presumably use a client to both publish events to whatever you're using to back these subscriptions, and then use the client to also subscribe, and then test that it behaves correctly.

I'm going to close this issue for now since it's been a while there was last any activity on it, and it was not clear what action to take here.  I'm going to leave conversation open, so feel free to respond if you want to pursue this further.
