### ISSUE TITLE
How to use graphql-subscriptions with express-graphql

### ISSUE THREAD

**Issue by kenshero** [apollographql/graphql-subscriptions#42]
I try to create subscriptions schema. but hard for me.

Do you have example code for create subscriptions with express-graphql ?

Thank you

**Comment by Darkbladecr** [comment]
I recommend you have a look at the sample we created here:
https://github.com/abhiaiyer91/GraphQL-Chat

**Comment by dotansimha** [comment]
@kenshero 

I guess that this issue is more relevant to `subscriptions-transport-ws` package, because this package only manages the `PubSub` and the actual GraphQL subscriptions.

Basically, you can use `subscriptions-transport-ws` with any HTTP server, so you should be able to use it with `express-graphql` by using your Express app, wrap with `createServer`, and pass it to your `SubscriptionsServer` instance.

Take a look here for an example: http://dev.apollodata.com/tools/graphql-subscriptions/express.html (is uses `graphql-server-express`, but the implementation is the same, since you only need the `express` instance)

**Comment by perrosnk** [comment]
Is it possible to use `subscriptions-transport-ws` in `graphiQL` when using `express-graphql `?

**Comment by DxCx** [comment]
@perrosnk you can but you will have to do the integration yourself,
while if you will use `graphql-server-express` you have a graphiql version with support for subscription.

**Comment by riginoommen** [comment]
@perrosnk yes but can you share the steps how to do the integration

**Comment by grantwwu** [comment]
This question seems to be ill-posed... not a single person has replied here more than once... please create a new issue if you need more help!
