### ISSUE TITLE
JWT auth + refresh token issue

### ISSUE THREAD

**Issue by akaNightmare** [apollographql/graphql-subscriptions#68]
I use [JWT auth](https://github.com/auth0/express-jwt) for authentication and no problems with apollo client authentication because http://dev.apollodata.com/core/network.html#networkInterfaceMiddleware even when token refreshes, but I have the issue with graphql subscriptions authentication. According to https://github.com/apollographql/graphql-subscriptions/blob/master/.designs/authorization.md and https://github.com/apollographql/tools-docs/blob/master/tools/graphql-subscriptions/authentication.md token sets once only (`connectionParams: {token: 'some string'}` and `lazy: true`) on initialisation SubscriptionClient and it works fine, but not when token refreshes.

Technologies/libs which I use in my project:
* `vue`
* `vue-auth`
* `vue-apollo`
* `expressjs`
* `graphql-subscriptions`
* `subscriptions-transport-ws`
* `graphql`

**Comment by dotansimha** [comment]
@akaNightmare 
I think this issue is more related to `subscriptions-transport-ws` package. 
Since version 0.7.0 of the transport, you can specify `onOperation` and add custom logic to verify your token, then return a new context when each operation is executed.
You can see an example for this in GitHunt server example: https://github.com/apollographql/GitHunt-API/blob/master/api/server.js#L160

**Comment by DxCx** [comment]
@dotansimha websocket is not like http,
http will need to reconstruct the session every request, but on websocket
context can be constructed once on connect phase and then you can keep the session,
onOperation should just attach this session..

**Comment by dotansimha** [comment]
@DxCx I know, and we had a discussion about it few months ago. 
It's hard to maintain authentication with refresh tokens when using WebSocket connection, because validating it in during the construction of the connection is not enough sometimes, and validating it every message is probably too heavy.

In the ws transport with have both `onConnect` and `onOperation`, and I think that each application should choose the best flow and solution for itself.

**Comment by green-coder** [comment]
@akaNightmare  Keep in mind that the authentication process is just about verifying who is the entity you are talking to.

During a websocket session (assuming that you use a secure web socket), you know that the entity you are talking to is still the same than the one you verified at the opening of the session (via the `onConnect` callback). There is no need to refresh your JWT token if you don't have to it anymore.

**Comment by grantwwu** [comment]
If you're still having problems with this, please reply below... not quite sure if this is the right place for this.
