### ISSUE TITLE
How to set context for subscriptions?

### ISSUE THREAD

**Issue by myyellowshoe** [apollographql/graphql-subscriptions#76]
It seems that my resolver when responding to a subscription doesn't have access to the context variable, that are typically available with a non-subscription request. In my case I'm trying to push as many request that I can through a data loader.

Heres my resolver:
```
  resolve: (source, args, { loaders }) => {
    if (source.user.length === 0) {
      return {};
    }
    return loaders.users.load(source.user);
  },
```

Currently, I have something like this setup for standard graphql requests
```
  router.post('/graphql', graphqlKoa({
    schema,
    formatParams(params) {
      return params;
    },
    context: { loaders: {
      users: Loader(r.table('users'), 'id')
    } },
  }));
```

How might I set something like this with subscriptions?

**Comment by dotansimha** [comment]
Setting the GraphQL context for subscription is the transport's responsibility.
Just like you did with your `graphqlKoa`, you need to do the same with `subscriptions-transport-ws`, using the `onConnecting` callback.

**Comment by RayzRazko** [comment]
@dotansimha , does subscribe parameter of resolver accept context? In the documentation it is used without any arguments.

**Comment by dotansimha** [comment]
@RayzRazko , yeah, I called just like any other resolver, with `(rootValue, args, context, info)`.

**Comment by myyellowshoe** [comment]
Perfect, using the onConnect works great. Thanks for the guidance! Thanks @dotansimha.

**Comment by ravenscar** [comment]
I just wanted to add here that if you use `onConnect` to set up DataLoaders for subscriptions you should probably turn off caching.

The reason is that you usually want the DataLoaders to be short lived, e.g. for the duration of the request for a query. When setting them up in `onConnect` they will live for the duration of the websocket connection.

This can cause some funky behaviour if you change the data in the DB as it will use cached values instead of re-calling the database.

**Comment by tdfairbrother** [comment]
> I just wanted to add here that if you use onConnect to set up DataLoaders for subscriptions you should probably turn off caching.

@ravenscar Which cache are you referring to?

I am wanting to use new dataloader instances on every query and I'm not sure if it is possible from what I have been reading.

**Comment by myyellowshoe** [comment]
@ravenscar In my case i want the data to live for the live of the connection through onConnect, as I'm only to store the logged in user for that request.
Any other time I end up use data loaders I'm only using queries.

@tdfairbrother I use dataloaders on my queries and it works great. Why are thinking that it's not possible?

**Comment by tdfairbrother** [comment]
@myyellowshoe I edited my answer above to clarify what I meant. I didn't mean queries, I meant subscriptions. 

The onConnect callback is only called once per new subscription and not every time a subscription is resolved (subscribe resolver).

**Comment by tdfairbrother** [comment]
@myyellowshoe @ravenscar the cache property is on the Dataloader. It works now. Thanks for your help.

**Comment by ravenscar** [comment]
@myyellowshoe What I mean is if you set up a data loader per onConnect and don't disable caching it will live forever.

So say you ask it to load a value from the datastore, it will read it.

Then lets say the value is modified in the datastore (via a mutation, perhaps from this user perhaps another) and an even is created which will trigger the subscription.

The subscription re-uses the old dataloader, which doesn't query your datastore as it thinks it already knows the result from the previous query (but in reality it has the wrong result as the data has now changed). The subscription then delivers the old result to the client.

You won't run into this problem if you're not modifying things in your datastore though.

**Comment by ravenscar** [comment]
@tdfairbrother I use the same dataloaders for queries and mutations so I didn't want to turn off caching as it really hurts query performance (lots more reads from the DB).

I have a factory function called `getDataLoaders()` which returns a bucket object filled with instances of all the dataloaders I need. I call this for every `GET` request and on `onConnect` for subscriptions, and place the bucket on the context.

I added a `flush()` utility method to this bucket which will refresh all the dataloader instances with new ones.

When I am in the `resolve()` of a subscription the first thing I do is call `flush()` to make sure all my dataloaders are fresh, although I don't need to do this for queries.

This lets be keep caching enabled but is slightly error prone if I forget to call `flush()`.

I think a better way (although I haven't tried it) is to not put dataloaders themselves on the context but instead a factory function which will create or retrieve a dataloader based on a key, e.g. instead of `fooDataLoader` have `getFooDataLoader(key)` where key is derived from the request in queries, and the event in subscriptions.

**Comment by myyellowshoe** [comment]
@ravenscar yeah in my case i'm not modifying things in my subscription after the initial login. I'm largely only using it to store references to the user id, to verify login status. Good thought on using a flush method, i'll keep that in mind for the future.

**Comment by 97amarnathk** [comment]
What if I need to set the context for each individual subscription?

**Comment by Convly** [comment]
@97amarnathk did you try using the `onOperation` callback (instead of the onConnect)?
