### ISSUE TITLE
Async subscribe function

### ISSUE THREAD

**Issue by jperl** [apollographql/graphql-subscriptions#80]
I want to validate the subscription params with an async function. If I return a promise from the subscription resolver on the server the client errors with `Subscription must return Async Iterable`.

Can I submit a PR to allow an async subscribe function? And where should I look to make those changes?

**Comment by carlosbergfeld** [comment]
I think this depends more on the GraphQL spec (and reference implementation). That's actually [where the error comes from](https://github.com/graphql/graphql-js/blob/94a591f5d6b9e4313116457d3637f7cade250ed3/src/subscription/subscribe.js#L229). There's some discussion going on in https://github.com/graphql/graphql-js/issues/895.

Meanwhile, you can create a custom async iterator in which the `next` function only resolves if and when you validation passes, or calls your async iterator's `throw` function otherwise, which stops the subscription.

It looks like quite a few people are looking for this already, so maybe this library could have a simple `withValidation` helper to get them started, even though it would become unneeded when the spec gets updated.

**Comment by jperl** [comment]
Thanks for the reference. https://github.com/graphql/graphql-js/issues/895 seems like the proper issue.
